/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Enquiry = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'productInterest' : IDL.Text,
  'quantity' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'addEnquiry' : IDL.Func([Enquiry], [IDL.Text], []),
  'getEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Enquiry = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'productInterest' : IDL.Text,
    'quantity' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'addEnquiry' : IDL.Func([Enquiry], [IDL.Text], []),
    'getEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };